require_relative "./pieces/Rook.rb"
require_relative "./pieces/bishop.rb"
require_relative "./pieces/king.rb"
require_relative "./pieces/knight.rb"
require_relative "./pieces/nullpiece.rb"
require_relative "./pieces/pawn.rb"
require_relative "./pieces/queen.rb"